import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { Bot, CircleUserRound, FileText, GitBranch as Github, KeyRound, Layers3, LogOut, MessageSquarePlus, Network, Send, Sparkles } from 'lucide-react'
import { api } from './api/client'
import type { Conversation, Message, User } from './types'
import heroLandscape from './assets/hero-ink-landscape.png'
import './App.css'

const TOKEN_KEY = 'dqy-portfolio-token'
const github = 'https://github.com/dqyydq'

function Tags({ items }: { items: string[] }) { return <div className="reference-tags">{items.map(item => <span key={item}>{item}</span>)}</div> }

function Portfolio({ onEnter }: { onEnter: () => void }) {
  return <main className="reference-portfolio">
    <nav className="reference-nav"><strong>邓权耀 <i>·</i> 大模型应用研发</strong><div><a className="is-active" href="#home">首页</a><a href="#projects">项目</a><a href="#skills">技术栈</a><a href="#experience">经历</a><a href="#about">关于</a></div></nav>
    <section id="home" className="reference-hero"><div className="reference-hero-copy"><h1>邓权耀</h1><h2>大模型应用研发</h2><p>专注于大模型应用落地与工程化，擅长智能体设计、知识检索增强、企业级 API 服务与文档自动化，助力业务提效与智能化升级。</p><a href={github} target="_blank" rel="noreferrer"><Github size={25}/>GitHub</a></div><div className="reference-landscape" style={{ backgroundImage: `url(${heroLandscape})` }} aria-label="水墨山水背景" /></section>
    <section id="skills" className="reference-skills">
      <article><Network/><div><h3>LangGraph 智能体路由</h3><p>基于 LangGraph 构建多智能体路由与状态管理，支持条件路由、工具调用与可观测追踪。</p><Tags items={['LangGraph','Agent','路由策略','状态管理']}/></div></article>
      <article><Layers3/><div><h3>FastAPI + RAG 检索增强</h3><p>基于 FastAPI 构建高性能服务，结合 RAG 提升问答准确性，支持多源数据接入与混合检索。</p><Tags items={['FastAPI','RAG','向量检索','混合检索']}/></div></article>
      <article><FileText/><div><h3>金融文档自动化</h3><p>自动化处理财报与各类金融文档，完成信息抽取、结构化与校验，显著提升处理效率与准确性。</p><Tags items={['文档解析','信息抽取','结构化','质量校验']}/></div></article>
    </section>
    <section className="reference-lower">
      <article id="experience" className="reference-experience"><h2>工作经历</h2><div className="reference-timeline"><div><time>2023.07 — 至今</time><h3>大模型应用研发工程师</h3><p>负责企业级大模型应用的架构设计与落地，主导智能体平台与知识检索平台建设。</p><p>构建 FastAPI 服务与 RAG 能力，接入多源数据，支撑业务场景智能化升级。</p></div><div><time>2022.04 — 2023.06</time><h3>后端开发工程师</h3><p>参与核心业务系统设计与开发，沉淀高可用、可观测的工程实践。</p><p>优化系统性能与稳定性，支撑高并发场景下的业务需求。</p></div><div><time>2021.07 — 2022.03</time><h3>算法工程师（实习）</h3><p>参与自然语言处理与信息抽取相关项目，完成模型评估与工程化落地。</p></div></div><button>查看完整经历 <span>›</span></button></article>
      <article id="projects" className="reference-projects"><h2>精选项目</h2><Project icon={<Network/>} title="跨国银行流水自动核验 Agent（LangGraph）" text="上传 PDF 与 CSV 后，自动路由至对应国家与银行的解析器，提取交易字段并完成总额校验。" tags={['LangGraph','Agent','路由策略','可观测性']}/><Project icon={<Layers3/>} title="易商宝商户注册 Agent（FastAPI + RAG）" text="以对话引导商户完善银行卡、证件、营业执照、股东等信息，并完成多模态校验与表单同步。" tags={['FastAPI','RAG','OCR','多源数据']}/><Project icon={<FileText/>} title="Derm AI 云端多轮问诊" text="基于 RAG 的皮肤知识库与多轮问诊项目，采用 FastAPI 提供高性能服务。" tags={['文档解析','信息抽取','结构化','质量校验']}/><button>查看全部项目 <span>›</span></button></article>
      <aside id="about" className="reference-assistant"><h2>AI 助手（仅登录用户可用）</h2><div className="reference-bubble-row"><Bot/><p>你好，我是你的专属 AI 助手，<br/>可以解答你对我项目与技术的疑问。</p></div><div className="reference-bubble-row is-user"><p>这个问答基于 DeepSeek 模型，<br/>请先在设置中配置你的 API Key。</p><CircleUserRound/></div><ul><li>基于 DeepSeek 模型</li><li>你的 API Key 仅用于本次会话，不会被存储</li><li>开启深度思考，获取更高质量回答</li></ul><button onClick={onEnter}>去设置 API Key</button><small>说明：请使用你自己的 DeepSeek API Key</small></aside>
    </section>
  </main>
}

function Project({ icon, title, text, tags }: { icon: ReactNode; title: string; text: string; tags: string[] }) { return <div className="reference-project"><div className="project-icon">{icon}</div><div><h3>{title}</h3><p>{text}</p><Tags items={tags}/></div></div> }

function Auth({ onAuthenticated }: { onAuthenticated: (token: string, user: User) => void }) {
  const [mode, setMode] = useState<'login' | 'register' | 'verify'>('login'); const [email,setEmail]=useState(''); const [user_name,setName]=useState(''); const [password,setPassword]=useState(''); const [code,setCode]=useState(''); const [notice,setNotice]=useState('')
  const submit=async(e:FormEvent)=>{e.preventDefault();setNotice('');try{if(mode==='register'){await api.register({email,user_name,password});setMode('verify');setNotice('验证码已发送，请查收邮箱。');return}if(mode==='verify'){await api.verifyEmail({email,code});setMode('login');setNotice('邮箱已验证，请登录。');return}const token=await api.login({email,password});onAuthenticated(token.access_token,await api.getMe(token.access_token))}catch(err){setNotice(err instanceof Error?err.message:'操作失败')}}
  return <main className="auth-page"><button className="back" onClick={()=>history.back()}>← 返回主页</button><form onSubmit={submit}><p className="eyebrow">PRIVATE AI ASSISTANT</p><h1>{mode==='login'?'登录':'创建并验证账户'}</h1>{mode==='register'&&<input placeholder="用户名" value={user_name} onChange={e=>setName(e.target.value)} required/>}<input type="email" placeholder="邮箱" value={email} onChange={e=>setEmail(e.target.value)} required/>{mode!=='verify'&&<input type="password" placeholder="至少 8 位密码" value={password} onChange={e=>setPassword(e.target.value)} required minLength={8}/>} {mode==='verify'&&<input placeholder="6 位验证码" value={code} onChange={e=>setCode(e.target.value)} required/>}{notice&&<p>{notice}</p>}<button type="submit">{mode==='login'?'登录':mode==='register'?'注册并发送验证码':'验证邮箱'}</button>{mode==='login'?<button type="button" className="link" onClick={()=>setMode('register')}>没有账号？注册</button>:<button type="button" className="link" onClick={()=>setMode('login')}>已有账号？登录</button>}</form></main>
}

function Chat({ token,user,onSignOut }: { token:string;user:User;onSignOut:()=>void }) {
  const [key,setKey]=useState(''); const [conversations,setConversations]=useState<Conversation[]>([]); const [active,setActive]=useState<Conversation|null>(null); const [messages,setMessages]=useState<Message[]>([]); const [draft,setDraft]=useState(''); const [error,setError]=useState(''); const [savingKey,setSavingKey]=useState(false)
  const suggestions=['介绍一下邓权耀的项目经历','跨国银行流水核验 Agent 是如何设计的？','你在 LangGraph 编排中负责了哪些部分？']
  const reload=async()=>{const cs=await api.listConversations(token);setConversations(cs);if(!active&&cs[0])setActive(cs[0])}
  useEffect(()=>{void reload()},[]); useEffect(()=>{if(active) api.listMessages(token,active.id).then(setMessages).catch(err=>setError(err instanceof Error?err.message:'加载会话失败')); else setMessages([])},[active])
  const saveKey=async()=>{if(!key.trim()) return;setSavingKey(true);setError('');try{await api.saveKey(token,key.trim());setKey('');location.reload()}catch(err){setError(err instanceof Error?err.message:'保存 API Key 失败')}finally{setSavingKey(false)}}
  const send=async(e:FormEvent)=>{e.preventDefault();if(!draft.trim())return;try{setError('');let c=active;if(!c){c=await api.createConversation(token,draft.slice(0,40));setActive(c);await reload()}await api.sendMessage(token,c.id,draft);setMessages(await api.listMessages(token,c.id));setDraft('')}catch(err){setError(err instanceof Error?err.message:'发送失败')}}
  return <main className="studio-shell"><aside className="studio-rail"><div><a className="studio-wordmark" href="#home"><span>DQ</span><b>邓权耀</b><small>PRIVATE AI</small></a><button className="studio-new" onClick={()=>setActive(null)}><MessageSquarePlus size={17}/>新建对话</button><p className="studio-rail-label">RECENT CONVERSATIONS</p><nav className="studio-conversations">{conversations.length?conversations.map(c=><button className={active?.id===c.id?'is-active':''} key={c.id} onClick={()=>setActive(c)}>{c.title}</button>):<p>新的提问会在这里出现。</p>}</nav></div><div className="studio-account"><div className="studio-avatar">{user.user_name.slice(0,1).toUpperCase()}</div><div><strong>{user.user_name}</strong><span>verified account</span></div><button title="退出登录" onClick={onSignOut}><LogOut size={17}/></button></div></aside><section className="studio-main"><header className="studio-header"><div><p>PRIVATE RESEARCH STUDIO</p><h1>{active?.title||'专属 AI 助手'}</h1></div><button className="studio-mobile-new" onClick={()=>setActive(null)}><MessageSquarePlus size={17}/>新对话</button></header><section className={`studio-key-strip ${user.has_deepseek_api_key?'is-ready':''}`}><KeyRound size={19}/><div><strong>{user.has_deepseek_api_key?'个人 API Key 已就绪':'配置你的 DeepSeek API Key'}</strong><span>{user.has_deepseek_api_key?`当前使用 ${user.deepseek_api_key_hint}`:'你的 Key 经过加密保存，仅用于你的对话请求。'}</span></div>{!user.has_deepseek_api_key&&<div className="studio-key-form"><input type="password" placeholder="DeepSeek API Key" value={key} onChange={e=>setKey(e.target.value)}/><button disabled={!key.trim()||savingKey} onClick={()=>void saveKey()}>{savingKey?'保存中…':'安全保存'}</button></div>}</section><section className="studio-thread">{messages.length?<div className="studio-message-list">{messages.map(m=><article key={m.id} className={`studio-message ${m.role}`}><span>{m.role==='user'?'你':'DQ AI'}</span><p>{m.content}</p></article>)}</div>:<div className="studio-welcome"><div className="studio-spark"><Sparkles size={25}/></div><p>你好，{user.user_name}</p><h2>从一个具体问题开始。</h2><span>这里可以了解我的项目、技术选择与大模型应用实践。</span><div>{suggestions.map(item=><button key={item} onClick={()=>setDraft(item)}>{item}</button>)}</div></div>}{error&&<p className="studio-error">{error}</p>}</section><form className="studio-composer" onSubmit={send}><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder={user.has_deepseek_api_key?'问我任何有关项目或技术的问题…':'先完成 API Key 配置，即可开始对话'} disabled={!user.has_deepseek_api_key}/><div><span>Enter 发送 · Shift + Enter 换行</span><button disabled={!user.has_deepseek_api_key||!draft.trim()} aria-label="发送消息"><Send size={19}/></button></div></form></section></main>
}

export default function App(){const [token,setToken]=useState(localStorage.getItem(TOKEN_KEY)||'');const [user,setUser]=useState<User|null>(null);const [auth,setAuth]=useState(false);useEffect(()=>{if(token)api.getMe(token).then(setUser).catch(()=>setToken(''))},[token]);if(token&&user)return <Chat token={token} user={user} onSignOut={()=>{localStorage.removeItem(TOKEN_KEY);setToken('');setUser(null)}}/>;return auth?<Auth onAuthenticated={(t,u)=>{localStorage.setItem(TOKEN_KEY,t);setToken(t);setUser(u)}}/>:<Portfolio onEnter={()=>setAuth(true)}/>}
